package org.model;
// Generated 2016-11-10 15:35:53 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private Integer bookId;
	private String bookName;
	private String isbn;
	private String author;
	private String publisher;
	private Integer page;
	private Date pubDate;
	private Double price;
	private Integer cnum;
	private Integer snum;
	private String summary;
	private String photoCover;
	private String photoSpine;
	private Integer categoryId;

	public Book() {
	}

	public Book(String bookName, String isbn, String author, String publisher, Integer page, Date pubDate, Double price,
			Integer cnum, Integer snum, String summary, String photoCover, String photoSpine, Integer categoryId) {
		this.bookName = bookName;
		this.isbn = isbn;
		this.author = author;
		this.publisher = publisher;
		this.page = page;
		this.pubDate = pubDate;
		this.price = price;
		this.cnum = cnum;
		this.snum = snum;
		this.summary = summary;
		this.photoCover = photoCover;
		this.photoSpine = photoSpine;
		this.categoryId = categoryId;
	}

	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public Integer getPage() {
		return this.page;
	}

	public void setPage(Integer page) {
		this.page = page;
	}

	public Date getPubDate() {
		return this.pubDate;
	}

	public void setPubDate(Date pubDate) {
		this.pubDate = pubDate;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Integer getCnum() {
		return this.cnum;
	}

	public void setCnum(Integer cnum) {
		this.cnum = cnum;
	}

	public Integer getSnum() {
		return this.snum;
	}

	public void setSnum(Integer snum) {
		this.snum = snum;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getPhotoCover() {
		return this.photoCover;
	}

	public void setPhotoCover(String photoCover) {
		this.photoCover = photoCover;
	}

	public String getPhotoSpine() {
		return this.photoSpine;
	}

	public void setPhotoSpine(String photoSpine) {
		this.photoSpine = photoSpine;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

}
