package org.model;
// Generated 2016-11-1 19:51:35 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Lend generated by hbm2java
 */
public class Lend implements java.io.Serializable {

	private Integer id;
	private Integer bookId;
	private Integer readerId;
	private Date ltime;
	private Date stime;

	public Lend() {
	}

	public Lend(Integer bookId, Integer readerId, Date ltime, Date stime) {
		this.bookId = bookId;
		this.readerId = readerId;
		this.ltime = ltime;
		this.stime = stime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	public Integer getReaderId() {
		return this.readerId;
	}

	public void setReaderId(Integer readerId) {
		this.readerId = readerId;
	}

	public Date getLtime() {
		return this.ltime;
	}

	public void setLtime(Date ltime) {
		this.ltime = ltime;
	}

	public Date getStime() {
		return this.stime;
	}

	public void setStime(Date stime) {
		this.stime = stime;
	}

}
