package org.model;
// Generated 2016-11-10 15:35:53 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Userinfo generated by hbm2java
 */
public class Userinfo implements java.io.Serializable {

	private Integer readerId;
	private String email;
	private String phoneNo;
	private String address;
	private String sex;
	private Date birthday;

	public Userinfo() {
	}

	public Userinfo(String sex) {
		this.sex = sex;
	}

	public Userinfo(String email, String phoneNo, String address, String sex, Date birthday) {
		this.email = email;
		this.phoneNo = phoneNo;
		this.address = address;
		this.sex = sex;
		this.birthday = birthday;
	}

	public Integer getReaderId() {
		return this.readerId;
	}

	public void setReaderId(Integer readerId) {
		this.readerId = readerId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

}
