package org.model;
// Generated 2016-11-10 15:35:53 by Hibernate Tools 4.3.1.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String email;
	private String userName;
	private String password;
	private int isAdmin;

	public User() {
	}

	public User(String email, String userName, String password, int isAdmin) {
		this.email = email;
		this.userName = userName;
		this.password = password;
		this.isAdmin = isAdmin;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(int isAdmin) {
		this.isAdmin = isAdmin;
	}

}
